name = "hamsoya-backend"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Wrangler v4 configuration
minify = false

# Development environment
[env.development]
name = "hamsoya-backend-dev"
[env.development.vars]
NODE_ENV = "development"
FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "http://localhost:5000"

# Production environment
[env.production]
name = "hamsoya-backend-prod"
[env.production.vars]
NODE_ENV = "production"
FRONTEND_URL = "https://hamsoya.vercel.app"
BACKEND_URL = "https://hamsoya-backend-prod.ahmedriazbepari.workers.dev"
REDIS_URL = "https://civil-tetra-32132.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "{{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
JWT_ACCESS_SECRET = "b01f932f9bdcaf3d"
JWT_REFRESH_SECRET = "ac3ccfd6e2c235ff"
RESEND_API_KEY = "{{ secrets.RESEND_API_KEY }}"
FROM_EMAIL = "hello@hamsoya.com"
FROM_NAME = "Hamsoya"
GOOGLE_CLIENT_ID = "{{ secrets.GOOGLE_CLIENT_ID }}"
GOOGLE_CLIENT_SECRET = "{{ secrets.GOOGLE_CLIENT_SECRET }}"
GOOGLE_CALLBACK_URL = "https://hamsoya-backend-prod.ahmedriazbepari.workers.dev/api/auth/google/callback"
SESSION_SECRET = "hamsoya-super-secret-session-key-2024-change-in-production"
SESSION_NAME = "hamsoya_session"
SESSION_MAX_AGE = "86400000"
DATABASE_URL = "postgresql://neondb_owner:npg_tOvMo7u4UYqc@ep-lively-mountain-a15oq90l-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# Default environment variables (use wrangler secret put for sensitive values)
[vars]
NODE_ENV = "development"
FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "http://localhost:5000"
REDIS_URL = "https://civil-tetra-32132.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AX2EAAIjcDFhODQxOWZmYTMzMDg0ZDkxOTMyNTNiMDQ5MDk2OTJhM3AxMA"
RESEND_API_KEY = "re_test_key"
FROM_EMAIL = "hello@localhost"
FROM_NAME = "Hamsoya Dev"

# KV namespaces for session storage if needed
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects if needed for real-time features
# [[durable_objects.bindings]]
# name = "CHAT_ROOMS"
# class_name = "ChatRoom"

# R2 buckets for file storage if needed
# [[r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "hamsoya-uploads"

# Build configuration
[build]
command = "echo 'Skipping TypeScript check for Cloudflare Workers deployment'"

# Routes for production deployment
# Comment out routes if domain is not yet configured in Cloudflare
# [[routes]]
# pattern = "hamsoya.vercel.app/api/*"
# zone_name = "hamsoya.vercel.app"

# [[routes]]
# pattern = "hamsoya.vercel.app/trpc/*"
# zone_name = "hamsoya.vercel.app"

# Limits and performance - commented out for Free plan
# [limits]
# cpu_ms = 50000

# Analytics
# [analytics_engine_datasets]
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
